version: '3.4'

services:
  dockertutorialconsole:
    image: ${DOCKER_REGISTRY-}dockertutorialconsole
    build:
      context: .
      dockerfile: DockerTutorialConsole/Dockerfile
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root