version: '3.4'

services:
  dockertutorialconsole:
    image: ${DOCKER_REGISTRY-}dockertutorialconsole
    build:
      context: .
      dockerfile: DockerTutorialConsole/Dockerfile
  database:
    image: mongo
    restart: always